"""add news title hash

Revision ID: 81e3f5f896e8
Revises: 3f0f8e618dc7
Create Date: 2026-09-04 23:03:27.058028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81e3f5f896e8'
down_revision: Union[str, Sequence[str], None] = '3f0f8e618dc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # Add column temporarily as nullable
    op.add_column(
        'news',
        sa.Column(
            'title_hash',
            sa.String(length=64),
            nullable=True,
        ),
    )

    # Generate title hashes for existing records
    connection = op.get_bind()

    connection.execute(
        sa.text(
            """
            UPDATE news
            SET title_hash = md5(lower(regexp_replace(title, '[^a-zA-Z0-9]+', ' ', 'g')))
            WHERE title_hash IS NULL
            """
        )
    )

    # Make the column mandatory
    op.alter_column(
        'news',
        'title_hash',
        existing_type=sa.String(length=64),
        nullable=False,
    )

    # Add index
    op.create_index(
        op.f('ix_news_title_hash'),
        'news',
        ['title_hash'],
        unique=False,
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_title_hash'), table_name='news')
    op.drop_column('news', 'title_hash')
    # ### end Alembic commands ###
